### ISSUE TITLE
Cannot add service

### ISSUE THREAD

**Issue by kylebrowning** [d8-contrib-modules/services#18] opened 2015-08-26 02:50 UTC
Clean Install drupal beta-14,

Enable Services.

Goto http://drupal-8-0-0-beta14.dd/admin/structure/service_api

And click Add Service API

<em class="placeholder">Recoverable fatal error</em>: Argument 1 passed to Drupal\services\Form\ServiceAPIForm::__construct() must be an instance of Drupal\services\Form\PluginManagerInterface, instance of Drupal\services\ServiceDefinitionPluginManager given, called in /Users/kylebrowning/Sites/devdesktop/drupal-8.0.0-beta14/modules/services/src/Form/ServiceAPIForm.php on line 28 and defined in <em class="placeholder">Drupal\services\Form\ServiceAPIForm-&gt;__construct()</em> (line <em class="placeholder">31</em> of <em class="placeholder">/Users/kylebrowning/Sites/devdesktop/drupal-8.0.0-beta14/modules/services/src/Form/ServiceAPIForm.php</em>).

**Comment by nerdstein** [comment] 2015-08-27 01:10
I could not reproduce (on 8.x-dev, not beta14), but it looks like it couldn't reflect the PluginManager. I explicitly added a reference to the designated class in https://github.com/d8-contrib-modules/services/pull/20

**Comment by nerdstein** [comment] 2015-08-27 01:28
Closing

**Closed as completed by nerdstein** 2015-08-27 01:28 UTC
